name: pgvector

services:
  pgvector:
    image: pgvector/pgvector:pg16
    container_name: pgvector
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=123
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgvector_data:

